# This is a workflow to create a new OpenRelik VSCode Extension Release
name: OpenRelik VSCode Extension Release

on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        run: |
          npm install -g @vscode/vsce
          npm install
      - name: Package Extension
        run: vsce package --target linux-x64 linux-arm64 darwin-x64 darwin-arm64 --out openrelik-extension.vsix
      - name: Upload Extension as a release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: openrelik-extension.vsix
          asset_name: openrelik-extension.vsix
          asset_content_type: application/zip
